import 'package:equatable/equatable.dart';

/// ## HistoryItem
/// A simple data model representing a single history entry stored in Hive.
/// Each item has a unique key and the associated text input.
///
/// This class extends `Equatable` for value-based equality, allowing
/// easy comparison of items in lists or state management.
///
/// ### Properties
/// - `key`: A unique identifier for the item (typically generated by Hive).
/// - `text`: The text content of the history item.



class HistoryItem extends Equatable {
  final dynamic key; 
  final String text;

  const HistoryItem({required this.key, required this.text});

  @override
  List<Object?> get props => [key, text];
}
